// Pre-renders lib/icons.ts (SVG data URLs) to PNG data URLs, because the
// real-device WeChat <image> component does not reliably render SVG data
// URLs (the devtools simulator does, which hides the problem).
//
// Usage:  node scripts/gen-icons.mjs   (from miniprogram/)
// Output: src/lib/icons.gen.ts — committed, imported by the pages.
import { execSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
// sharp lives in the repo-root node_modules (Next.js backend).
const require = createRequire(join(root, "..", "package.json"));
const sharp = require("sharp");

const tmp = mkdtempSync(join(tmpdir(), "speaker-icons-"));
const bundle = join(tmp, "icons.mjs");
execSync(`npx esbuild src/lib/icons.ts --bundle --format=esm --outfile="${bundle}"`, {
  cwd: root,
  stdio: "inherit",
});

const { ICONS, MIST, TREND_CHART } = await import(pathToFileURL(bundle).href);

function svgFromDataUrl(dataUrl) {
  const base64 = dataUrl.replace(/^data:image\/svg\+xml;base64,/, "");
  return Buffer.from(base64, "base64");
}

async function toPng(dataUrl, density) {
  const png = await sharp(svgFromDataUrl(dataUrl), { density }).png().toBuffer();
  return `data:image/png;base64,${png.toString("base64")}`;
}

const iconEntries = [];
for (const [name, dataUrl] of Object.entries(ICONS)) {
  // 24px viewBox at density 288 -> 96px PNG (crisp on 3x screens).
  iconEntries.push(`  ${name}: "${await toPng(dataUrl, 288)}",`);
}
const mist = await toPng(MIST, 216);
const chart = await toPng(TREND_CHART, 216);

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// PNG versions of lib/icons.ts: real-device <image> doesn't render SVG data
// URLs, so the SVGs are pre-rasterized at build time. Re-run the script after
// changing lib/icons.ts.

export const ICONS = {
${iconEntries.join("\n")}
} as const;

export const MIST = "${mist}";

export const TREND_CHART = "${chart}";
`;

const outFile = join(root, "src", "lib", "icons.gen.ts");
writeFileSync(outFile, out);
rmSync(tmp, { recursive: true, force: true });
console.log(`wrote ${outFile} (${(out.length / 1024).toFixed(0)} KB)`);
